version: '3.8'

services:
  reitorly:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.10
        DUCKDB_VERSION: 0.10.2
    volumes:
      - data:/app/data
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "python", "-c", "import gorilla_cli; import duckdb"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  data:
    driver: local
